Update members 2024-2025
stakRedakcija/stak-web pull request #22
Opened 2024-11-18 21:47 UTC by OGADAMo

This pull request updates the members list on the website for the 2024 year. The main changes include:

1. Adding new members and removing outdated ones
3. Updating descriptions for existing members
4. Image updates:
  -   New images for members added in JPG and WebP formats
  -   Optimized image sizes and quality
  -   Placeholder images set for members without photos

5. Impressum update:
  - Manually added new members and removed the outdated ones
  - Formatting and order have been verified to align with current standards

Reviewer: @Adam Marjanovic

2024-11-18 21:59 UTC, stakRedakcija requested changes

2024-11-18 21:59 UTC, stakRedakcija commented on static/clanovi/eva-petrovic – kopija.jpg
Please rename

2024-11-18 21:59 UTC, stakRedakcija commented on static/clanovi/rea-soboscan.jpg
Please resize to 400 (on the larger side)

2024-11-18 22:37 UTC, OGADAMo commented on static/clanovi/eva-petrovic – kopija.jpg
Renamed

2024-11-18 22:37 UTC, OGADAMo commented on static/clanovi/rea-soboscan.jpg
Resized to 400

2024-11-19 21:31 UTC, stakRedakcija commented on static/clanovi/rea-soboscan.jpg
![image](https://github.com/user-attachments/assets/f7590d61-8e1c-4a9b-9ec5-d6393521710f)
🤔

2024-11-19 21:31 UTC, stakRedakcija commented on static/clanovi/morana-zuro.jpg
This one may need resizing too

2024-11-19 21:31 UTC, stakRedakcija commented on static/clanovi/mateo-cuvalo.jpg
Resize this one too, please

2024-11-19 21:32 UTC, stakRedakcija commented on static/clanovi/matea-kucljak.jpg
This one needs resizing

2024-11-19 21:32 UTC, stakRedakcija commented on static/clanovi/marta-pamuklic.jpg
Resize please

2024-11-19 21:32 UTC, stakRedakcija commented on static/clanovi/luka-arbutina.jpg
This one needs resizing

2024-11-19 21:32 UTC, stakRedakcija commented on static/clanovi/kaja-culjak.jpg
Resize pls

2024-11-19 21:32 UTC, stakRedakcija commented on static/clanovi/adam-marjanovic.jpg
Resize pls

2024-11-28 20:13 UTC, stakRedakcija approved these changes

2024-11-28 20:13 UTC, merged